### ISSUE TITLE
terminal search issues

### ISSUE THREAD

**Issue by rezso** [mate-desktop/mate-desktop#121]
The mate_desktop_prepend_terminal_to_vector() tries to find a terminal.
This is a good thing, but:
- the -x option in mate-terminal (and in gnome-terminal) is buggy,
- the function doesn't looks for widely used terminals (f. ex. xfce4-terminal, eterm, roxterm),
- xterm is exists in the list, but this is the "fallback" terminal, so if the xterm not exists, the function tries to run xterm :)
My solution for these issues:
https://gist.github.com/rezso/5e08ab28dfcb8e4b12d6

**Comment by monnerat** [comment]
IMHO, glib will never be patched for mate :-( The fix has to be done in mate and, as said before, is not easy.
However, here is a very dirty workaround: if gnome-terminal is not installed, as root do:

# ln -s /usr/bin/mate-terminal /usr/bin/gnome-terminal

It will not respect the preferred terminal, but at least will schedule the mate-terminal.

**Comment by madjxatw** [comment]
There seems to be two issues
* If change preferred terminal from mate-terminal to any other, "Run in Terminal" doesn't work properly in Caja. On my machine, need to manually change exec-arg from -x to -e. Any advice?
* Make a "Application in Terminal" launcher on desktop, it always calls rxvt which should be the first alternative if finds instead of mate-terminal. After I make the soft link /usr/bin/gnome-terminal linking to /usr/bin/mate-terminal, it's fixed.

**Comment by monsta** [comment]
Time to close it and open new issues in relevant projects. This is not related to ```mate-desktop``` library.
