### ISSUE TITLE
mate-bg.c find_best_size can return NULL, causes caja SEGV

### ISSUE THREAD

**Issue by matobinder** [mate-desktop/mate-desktop#170]
So I've been setting up some VMs running TIgerVNC Server, and VNC'ing into them with TigerVNCViewer.  I'm not sure why, but when when you have a desktop background wallpaper, resizing the desktop causes Caja to crash. I looked into this and I see that mate-bg.c:find_best_size() can, and does return NULL if it doesn't find  a "best".  In my case this cases get_pixbuf_for_size to SEGV, because it tries to defreference that NULL poninter.  In all uses of find_best_size, it looks like it assumes that it will NOT return NULL, so the crash can occur in other instances as well.

I was able to stop Caja from crashing, by not having a background image... i.e.

dconf write /org/mate/desktop/background/picture-filename "''"

So, I think we need to fix find_best_size() to make sure it returns something. Instead of NULL. I don't have a good dev environment to test anything so I'm not comfortable trying to make a code change/pull request with out really trying this out myself.

But I would suggest the following... code snippt fom mate-bg.c:find_best_size()

....
for (pass = 0; pass < 2; pass++) {
        for (s = sizes; s; s = s->next) {
        FileSize *size = s->data;

```
    //here's my suggested fix... so best ALWAYS at least gets assigned once.
    if  (best == NULL) {
         best = size;
     }
    //end my fix

    i f (pass == 0 && (size->width < width || size->height < height))
           continue;
```

....
##

**Comment by olivergg** [comment]
I have the same issue on an ArchLinux machine. I had to add X-MATE-AutoRestart=false to prevent the infinite loop.
Now, I can log in... but I can't start the file manager anymore : 
I've got the following error in dmesg : 
``` caja[702]: segfault at 125e84 ip b6b76c00 sp bfc355f0 error 4 in libgobject-2.0.so.0.4400.1[b6b45000+5a000]```
Can you confirm this is the same issue (segfault in libgobject) ?

**Comment by raveit65** [comment]
@matobinder 
I can do a sratch koji build for epel7 with your fix for testing.
I do not use vnc, so i am not able to confirm if this really works.

**Comment by monsta** [comment]
The question is, whether the patch is just a suggestion for us, or did @matobinder actually tested it?

Here's why I'm asking. Looking at the stacktrace posted at https://github.com/mate-desktop/caja/issues/413#issuecomment-100078353, I see that ```get_pixbuf_for_size``` was called with zero value for both ```best_width``` and ```best_height``` arguments. It means that in ```draw_each_monitor``` function, just before the call to ```get_pixbuf_for_size```, ```gdk_screen_get_monitor_geometry``` filled ```GdkRectangle``` variable with zero width/height values.

I don't know if it's a valid behavior in GDK, or is it a bug. But the problem is that with zero height value things will go wrong earlier than the proposed fix will be reached. There are two places before that code where width is divided by height - that's an instant crash in case height is zero.

**Comment by matobinder** [comment]
Was just looking back at some stuff I had posted. I don't see this issue anymore. The code doesn't return null in that case so this crash doesn't happen.
