### ISSUE TITLE
Please add an option to set the max volume above 100%

### ISSUE THREAD

**Issue by michaelmrose** [mate-desktop/mate-desktop#246]
Some combinations of hardware + source are too quiet at 100% Adjusting the sound above 100% requires right clicking on the sound applet selecting properties adjusting it to the desired spot then if you use the normal volume control keys at this point will put the sound below the 100% threshold once again requiring the above procedure.  Rather than having a fixed boundry at  100% it would be nice if there was an option for this.

**Comment by raveit65** [comment]
Above 100% for a source means the sound is distorted for a normal input.

**Comment by michaelmrose** [comment]
For some inputs read movies with highly variable sound levels with the sound turned up to 100% the quiet parts are too low to understand conversation and the only practical way to enjoy some movies at all on the machine is to turn the quiet parts up higher.  This doesn't sound remotely distorted in this case.

My fix was to bind the volume up/down keys to scripts that turn the volume up/down in 5% increments and have it actually max out at 130 instead of 100%.  This misses out on the visual feedback of the volume meter that pops up and its probably unusable to 90% of people using mint. Lacking an option to set the max it would perhaps still be nicer if it went up a bit past 100%.  If it sounds bad to people they just wont turn it up that much.

**Comment by michaelmrose** [comment]
Some other comments regarding turning audio past 100%

From http://askubuntu.com/questions/41348/why-can-the-volume-go-higher-than-100

"Overamplifying a volume is a good feature, especially for laptops where internal speakers are not loud. I was using this feature since Ubuntu (9.10) on my FujitsuSiemens SI1520. It helped me very much to listen to music."

"I use it when i listen to speeches that were recorded at rather low volume. It might distort music/sound effects etc but it is rather useful in those cases when you just can't listen because of bad recording."

From http://superuser.com/questions/146784/sound-volume-increase-beyond-100-whenever-possible-on-linux

"Some audio output from files or streams is too low. It is obvious that hardware is able to play the same sounds but louder but because of the data it just plays it at some low level even at 100% volume."

Should I dig up about a hundred more?

**Comment by flexiondotorg** [comment]
You can exceed 100% volume in the Sound Properties.

**Comment by michaelmrose** [comment]
@flexiondotorg you can if you don't mind only adjusting volume by right clicking an icon selecting properties fidling with a slider.  The entire point is that at volume=80% hitting XF86RaiseVolume will result in volume increasing, XF86LowerVolume will result in it decreasing.  If you are at 110% volume hitting either button will return you to 100% and thereafter hitting raisevolume will do nothing.

My compaint is twofold.  That you can't get over 100% in the first place just by hitting the volumeup key and that even if you DO manually set it higher the volume control keys behavior is broken after 100%.  Nobody manually sets the volume at 110% and hits volume up and expects the volume to go down.

**Comment by jichu4n** [comment]
+1

My use case: media center PC with MATE hooked up to living room TV. The volume of some DVDs and YouTube videos are just too low, and I find myself repeatedly opening up Sound Preferences and moving the slider to get to e.g. 110% or 120%. Then I'd often forget and press XF86RaiseVolume again for another video some time later, and the volume drops back to 100% and I have to do this again. This is really inconvenient on a remote keyboard trackpad.

Can we maybe add a checkbox in Sound Preferences, e.g. "Allow increasing volume above 100%", which would make XF86RaiseVolume go up to the max allowed in Sound Preferences?

**Comment by ltcmdata** [comment]
+1
This was standard with gnome-fallback-session.

**Comment by orschiro** [comment]
@ltcmdata do you know if current GNOME still has this feature?

**Comment by ltcmdata** [comment]
I'm sorry, I don't know. I am currently using Mate only. But a little while back under the sound settings of gnome flashback there was a checkbox to allow volume above 100%. I think such a checkbox is a great solution to the problem.

**Comment by orschiro** [comment]
I agree. Unity has/had this, too:

![image](https://user-images.githubusercontent.com/170947/34651361-a11b6446-f3cf-11e7-8e72-4dc485c1d655.png)

**Comment by sc0w** [comment]
bounty:

https://www.bountysource.com/issues/41100594-please-add-an-option-to-set-the-max-volume-above-100

**Comment by raveit65** [comment]
Done!

**Comment by thesquash** [comment]
As indicated immediately above, I have created a solution to this issue.  Unfortunately, the way the MATE Desktop's sound infrastructure integrates, I had to make three separate pull requests for just this one issue, so I'm sure that's going to be a pain in the behind to deal with -- but hopefully it's not *too* hard to verify and then merge three pull requests, right?

**Comment by rbuj** [comment]
The pulseaudio backend already returns [PA_VOLUME_UI_MAX](https://freedesktop.org/software/pulseaudio/doxygen/volume_8h.html#a353b44010677b005abd390af732eb86e) = ([pa_sw_volume_from_dB](https://freedesktop.org/software/pulseaudio/doxygen/volume_8h.html#ad638dfbc737f126e743584665ea8f557)(+11.0)) instead of [PA_VOLUME_NORM](https://freedesktop.org/software/pulseaudio/doxygen/volume_8h.html#aded56902e68e0f8ab576339bde55960e).

IMHO, you have to check that the mixer backend allows to exceed the 100% of the volume, for this reason it cannot be a global setting, since it depends on the active mixer backend.

```C
static guint
pulse_stream_control_get_max_volume (MateMixerStreamControl *mmsc)
{
    MateMixerStreamControlFlags flags;

    g_return_val_if_fail (PULSE_IS_STREAM_CONTROL (mmsc), (guint) PA_VOLUME_MUTED);

    flags = mate_mixer_stream_control_get_flags (mmsc);

    /*
     * From PulseAudio wiki:
     * For all volumes that are > PA_VOLUME_NORM (i.e. beyond the maximum volume
     * setting of the hw) PA will do digital amplification. This works only for
     * devices that have PA_SINK_DECIBEL_VOLUME/PA_SOURCE_DECIBEL_VOLUME set. For
     * devices that lack this flag do not extend the volume slider like this, it
     * will not have any effect.
     */
    if (flags & MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL)
        return (guint) PA_VOLUME_UI_MAX;
    else
        return (guint) PA_VOLUME_NORM;
}
```

https://github.com/mate-desktop/libmatemixer/blob/fc47f17a919e0320c1fa9aa24ab008540d9b2991/backends/pulse/pulse-stream-control.c#L686-L697

**Comment by thesquash** [comment]
OK, then -- how about keeping the "Allow volume to exceed 100%" a global setting, but only showing the checkbox in the Sound Preferences if the current output control's "maximum" volume is greater than its "normal" volume?

Otherwise, I don't really get what you're point is.  Sure, it's misleading to the user to offer an option and then potentially not be able to fulfill the user's choice -- I totally agree with that, which is why I suggested what I just did.  However, what you said about PulseAudio "already returning" the maximum volume in lieu of the "normal" volume is immaterial (as far as I can tell), because PulseAudio will return that value only when the **maximum** volume is queried.  Look at the code in `gvc-channel-bar.c` again closely.  Look in the function `update_adjustment_limits ()`, which starts on line 390:

    static void
    update_adjustment_limits (GvcChannelBar *bar)
    {
            gdouble minimum = 0.0;
            gdouble maximum = 0.0;

            if (bar->priv->control != NULL) {
                    minimum = mate_mixer_stream_control_get_min_volume (bar->priv->control);
                    if (bar->priv->extended)
                            maximum = mate_mixer_stream_control_get_max_volume (bar->priv->control);
                    else
                            maximum = mate_mixer_stream_control_get_normal_volume (bar->priv->control);
    }

Notice that the "maximum" volume, as far as the MATE volume adjustment widgets are concerned, is either the "max" volume of the control, or the "normal" volume, **depending on the `extended` property of the slider widget**.  In other words, the PulseAudio backend might "already" return an amplified "max" volume if possible, but that's totally immaterial if the things using the controls query not the "max" volume, but the "normal" volume instead.

I hope I made myself clear enough.  I'll deal with the checkbox and make it appear only when the volume can be adjusted above 100%, but there's not much else I can do (unless I misunderstood, in which case please clarify).

**Comment by rbuj** [comment]
If you want to keep the global setting then, it makes no sense to show the checkbox "Allow volume to exceed 100%" in the mixer. It might be more or less useful to show it in the applet. 

<img width="616" alt="Captura de pantalla 2022-08-03 a les 9 44 01" src="https://user-images.githubusercontent.com/10171411/182552794-042cfcbe-3d4c-4813-80c5-ec7a71f7dc07.png">

**Comment by rbuj** [comment]
@thesquash, I reviewed the PRs and, it doesn't matter if you can't add the checkbox to the applet / status icon. Great job! The code is very elegant and I really liked that you added the property to the channel bar to show or hide the mark text.

**Comment by lukefromdc** [comment]
Closing at the 3 PR's have been merged
