### ISSUE TITLE
high cpu usage in ubuntu 18.04

### ISSUE THREAD

**Issue by tecan** [mate-desktop/mate-desktop#328]
xorg consistantly uses around 20% cpu while running mate. gnome classic and gnome do not have this issue.

**Comment by lukefromdc** [comment]
I have never had this problem in MATE at any time, including on an Ubuntu-MATE 18.04 setup on an old single-core AMD Athlon 64.  What window manager are you using, and if using Marco are you using composition, and if using the compositor are you using software compositing or hardware compositing(gpu compositing via Compton)?

**Comment by tecan** [comment]
found out its actually the inhibitor applet. it uses 8% cpu itself and makes xorg jacked up to 20% from 5%

**Comment by lukefromdc** [comment]
You could also try my prebuilt 1.21 mate-power-manager Debian build from
https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme
It should install fine if you remove all mate-power-manager packages first, then install this one, though I have no idea if that might remove Ubuntu metapackages used to pull in current dependencies.

You would want to remove it and reinstall mate-power-manager from Ubuntu's repos once they start offering 1.20.2 or later, it would not be automatically replaced both due to a different package name and because it is a 1.21 development version that will never be in Ubuntu.

**Comment by monsta** [comment]
An additional fix from https://github.com/mate-desktop/mate-power-manager/pull/255 is also needed.
Closing this one - we already have it reported at https://github.com/mate-desktop/mate-power-manager/issues/248 and fixed. Now it's up to distro maintainers.
