### ISSUE TITLE
Dialog box is malformed with transparent area

### ISSUE THREAD

**Issue by adatum** [mate-desktop/mate-desktop#401]
#### Expected behaviour
Dialog box should not have transparent areas.

#### Actual behaviour
The right and bottom edges inside the Connection Information dialog box from Network Manager have transparent areas. In this case it shows the desktop background, but it will show anything "behind" it such as other windows.
![screenshot_connection_information](https://user-images.githubusercontent.com/9773655/61336888-1e66d480-a801-11e9-9d93-f8dfdbf59cf6.png)

Maybe there is an undesired transparent area inside the dialog box, or maybe the borders and title bar are drawn larger than the dialog box?

#### Steps to reproduce the behaviour
Open Connection Information by selecting it from the right-click menu of the Network Manager Applet in the system tray.

#### MATE general version
1.22.1

#### Package version
Not sure which package is responsible for this.

#### Linux Distribution
Fedora 30 MATE

**Comment by lukefromdc** [comment]
The dialog shown comes from network-manager-applet which is not a MATE application.  The transparent "excess window space" area appears with every theme I tested, so it's not a mate-themes bug. I have the extra transparent space in compiz-reloaded and metacity, so it's not a marco (window manager) bug. Since the space in question is not identified by GtkInspector and does not respond to the default background it may not be possible to fix this in any theme, and it's broken in Adwaita which is GNOME's default theme.

This is a bug in network-manager-applet so you should open an issue there.

**Comment by adatum** [comment]
Thank you for reproducing and confirming the issue. At least we now have a better idea of where the problem lies.
