### ISSUE TITLE
at-spi-bus-launcher

### ISSUE THREAD

**Issue by reno-a** [mate-desktop/mate-desktop#416]
#### MATE general version
1.22.2

#### Linux Distribution
Debian (Sid) Kernel 5.2.0-3-amd64 - Debian 5.2.17-1 (2019-10-06)

Problem : slow opening session and error message at closing "at-spi-bus-launcher" which requires to wait.

**Comment by sc0w** [comment]
It was fixed in https://github.com/mate-desktop/mate-session-manager/pull/223

and it was fixed in debian with the patch https://salsa.debian.org/debian-mate-team/mate-session-manager/commit/a5c83db01dcfcd6e0feb03de232e74953306e611

There is no version in debian with the patch by the moment, the upload is pending.
