### ISSUE TITLE
black boxes around title bar letters

### ISSUE THREAD

**Issue by bajabaq** [mate-desktop/mate-desktop#467]
#### Expected behaviour
when horizontal direction of window is shrunk, title bar background color remains the same

#### Actual behaviour
when horizontal direction of window is shrunk, title bar background color turns black around some letters

#### Steps to reproduce the behaviour
open document with long title bar
shrink window in horizontal direction 

#### MATE general version
1.20.4

#### Package version
1.20.0+5

#### Linux Distribution
Debian Linux Stable 4.19.160-2

#### Link to bugreport of your Distribution (requirement)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982805

![long-vs-short](https://user-images.githubusercontent.com/1300282/107884483-4b8ad580-6ec3-11eb-95bb-f21907ee61e5.png)

**Comment by lukefromdc** [comment]
First things first: the current supported MATE release is 1.24, version 1.20 is no longer maintained.

That said, this looks like an issue with marco, the MATE window manager unless of course you are running compiz (the only other current window manager I know of to support metacity themes. Current metacity does NOT). What you have are video artifacts, try using marco both with and without compositing and see if that helps. If you are able to build and install marco 1.24 as currently released, it may or may not solve your problem depending on whether it came from a bug that has since been fixed. Less likely is a metacity theme issue

I was unable to duplicate this with marco 1.25.0 from git master, using traditional-OK (which your gtk theme looks like). My test program was pluma, wiht a very long filename opened. No video artifacts in your theme or in mine.

**Comment by bajabaq** [comment]
Thanks for looking into this - and thanks for the correct termination: "video artifacts"
I'm on Debian Stable, so I get what I get (understand this may already be fixed)

I am running Marco (Adaptive compositor) and the TraditionalOK theme

Checking your suggestions:
Under "Window Preferences"->General->Compositing Manger I unchecked "Enable software compositing window manager.

Then under "MATE Tweak"->Windows->Window manager I selected Marco (No compositor)

Then opened a pdf using Atrl - still had the issue.

Tried with Marco (Compton GPU compositor) - still had issue

Since you're not having issues on marco 1.25, it likely got fixed. 
Closing this issue.
